name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@master
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@main
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
        cache: 'pnpm'

    - name: Setup Git Configuration
      shell: bash
      run: |
        git config --global user.email "corta.hugo@gmail.com"
        git config --global user.name "hugocxl"

    - name: Install dependencies
      shell: bash
      run: pnpm i --no-frozen-lockfile
