name: Dependabot auto-merge

on: pull_request_target

jobs:
  dependabot:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Git configuration
        run: |
          git config --global user.email "corta.hugo@gmail.com"
          git config --global user.name "hugocxl"

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create patch version
        run: pnpm version patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
