name: Tests

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm i

      - name: Run tests
        run: pnpm test

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
